name: wireguard
services:
  wireguard:
    image: ghcr.io/wireguard/wireguard
    container_name: wireguard
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: 3
    env_file:
      - $ENV
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
      # - NET_RAW # ⚠️ Uncomment if using Podman
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    environment:
      - LANG=en
      - WG_HOST=vpn.$SERVER
      - PASSWORD_HASH=$PASS
      - WG_DEFAULT_DNS=1.1.1.1
      - WG_PERSISTENT_KEEPALIVE=25
      - UI_TRAFFIC_STATS=true
      - UI_CHART_TYPE=1
      - UI_ENABLE_SORT_CLIENTS=true
    volumes:
      - $DATA/vpn:/etc/wireguard
    ports:
      - $NGINX:51820:51820/udp
      - $NGINX:51821:51821/tcp
