name: mssql
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=$DB_PASSWORD
    ports:
      - '1433:1433'
    healthcheck:
      test: ['CMD-SHELL', "/opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P $DB_PASSWORD -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
