---
name: bazarr
services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - mediatek
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - $DATA/bazarr/config:/config
      - $DATA/movies:/movies
      - $DATA/tv:/tv
    ports:
      - 6767:6767

networks:
  mediatek:
    external: true
