name: redis
services:
  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    security_opt:
      - no-new-privileges:true
    volumes:
      - $DATA/redis:/data
    ports:
      - '6379:6379'
    networks:
      - db
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  db:
    external: true
