name: pg
services:
  pg:
    image: postgis/postgis:17-3.5
    container_name: pg
    restart: unless-stopped
    security_opt:
      - no-new-privileges
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
      TZ: $TZ
      PGTZ: $TZ
    volumes:
      - ${DATA}/pg:/var/lib/postgresql
    ports:
      - '5432:5432'
    networks:
      - pg
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  pg:
    external: true
